"""Add category relationship to product

Revision ID: 3d29f2c3ad12
Revises: 7bccfbdbda2b
Create Date: 2024-11-29 14:41:38.583873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d29f2c3ad12'
down_revision: Union[str, None] = '7bccfbdbda2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
