"""Add stock_quantity to products

Revision ID: a7b7e19b7bc9
Revises: 8a9e7ac3b231
Create Date: 2024-11-22 09:03:56.897861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b7e19b7bc9'
down_revision: Union[str, None] = '8a9e7ac3b231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock_quantity')
    # ### end Alembic commands ###
