"""Add category relationship to product

Revision ID: ad907d732dfa
Revises: 3d29f2c3ad12
Create Date: 2024-11-29 15:06:11.306667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ad907d732dfa'
down_revision: Union[str, None] = '3d29f2c3ad12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_index('ix_categories_id', table_name='categories')
    op.create_index(op.f('ix_categories_category_id'), 'categories', ['category_id'], unique=False)
    op.drop_column('categories', 'id')
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    op.add_column('categories', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_categories_category_id'), table_name='categories')
    op.create_index('ix_categories_id', 'categories', ['id'], unique=False)
    op.drop_column('categories', 'category_id')
    # ### end Alembic commands ###
